In [3]:
import pandas as pd

df = pd.read_csv("data.csv")

remove = []
remove.append(df.columns[0])
for rem in df.columns[6:37]:
    remove.append(rem)
remove.extend(["WDF2_x", "WDF5_x", "WSF2_x", "WSF5_x", "WDF2_y", "WDF5_y", "WSF2_y", "WSF5_y", "STATION_y",
               "FL_DATE", "OP_UNIQUE_CARRIER", "ORIGIN", "DEST", "CRS_DEP_TIME"])
X = df.drop(remove, axis = 1)
for col in X.columns:
    print(col)

AWND_x
PGTM_x
PRCP_x
SNOW_x
SNWD_x
TAVG_x
TMAX_x
TMIN_x
WT01_x
WT02_x
WT03_x
WT04_x
WT05_x
WT06_x
WT07_x
WT08_x
WT09_x
AWND_y
PGTM_y
PRCP_y
SNOW_y
SNWD_y
TAVG_y
TMAX_y
TMIN_y
WT01_y
WT02_y
WT03_y
WT04_y
WT05_y
WT06_y
WT07_y
WT08_y
WT09_y

In [5]:
def onehot(df, column):
    title = df[column].unique()
    header = [column + s for s in title]
    onehot = []
    for i in df[column]:
        result = []
        for j in title:
            if i == j:
                result.append(1)
            else:
                result.append(0)
        onehot.append(result)
    return pd.DataFrame(onehot, columns = header)
X = pd.concat([X, onehot(df, "OP_UNIQUE_CARRIER"), onehot(df, "ORIGIN"), onehot(df, "DEST")], axis = 1)
X

,AWND_x,PGTM_x,PRCP_x,SNOW_x,SNWD_x,TAVG_x,TMAX_x,TMIN_x,WT01_x,WT02_x,...,ORIGINMCO,DESTSEA,DESTMCO,DESTDEN,DESTSFO,DESTDFW,DESTLAX,DESTATL,DESTJFK,DESTLAS
0,9.4,0.0,0.07,0.0,0.0,51.0,57.0,45.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,0
1,9.4,0.0,0.07,0.0,0.0,51.0,57.0,45.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,0
2,9.4,0.0,0.07,0.0,0.0,51.0,57.0,45.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,0
3,9.4,0.0,0.07,0.0,0.0,51.0,57.0,45.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,0
4,9.4,0.0,0.07,0.0,0.0,51.0,57.0,45.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82707,4.7,1555.0,0.00,0.0,0.0,62.0,77.0,50.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
82708,4.7,1555.0,0.00,0.0,0.0,62.0,77.0,50.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
82709,4.7,1555.0,0.00,0.0,0.0,62.0,77.0,50.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
82710,4.7,1555.0,0.00,0.0,0.0,62.0,77.0,50.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
82711,4.7,1555.0,0.00,0.0,0.0,62.0,77.0,50.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0

In [118]:
vals = []
for index, row in df.iterrows():
    if (row["WEATHER_DELAY"] > 0):
        vals.append(row["WEATHER_DELAY"])
    else:
        vals.append(row["NAS_DELAY"]*0.55) # 55% of NAS Delays are due to weather
df['Y'] = vals
Y = pd.DataFrame(vals)
Y

          0
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       5.5
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
...     ...
82682   0.0
82683  12.1
82684   8.8
82685   0.0
82686   0.0
82687   0.0
82688   0.0
82689   0.0
82690   0.0
82691   0.0
82692   0.0
82693   0.0
82694   0.0
82695   0.0
82696   0.0
82697   0.0
82698   0.0
82699   0.0
82700   0.0
82701   0.0
82702   0.0
82703   0.0
82704   0.0
82705   0.0
82706   0.0
82707   0.0
82708   0.0
82709   0.0
82710   0.0
82711   0.0

[82712 rows x 1 columns]

In [119]:
X.to_csv('X1.csv')
Y.to_csv('Y1.csv')